'use client';
import {useBoardWebTools} from './web-tools';
import {useEffect,useState} from 'react';
import {ChevronDown,ChevronRight,Plus,Search,Layers,Trash2,X,RotateCcw,LockKeyhole,ExternalLink,FolderKanban,Activity,RefreshCw} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Progress} from '@/components/ui/progress';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {statuses,type Board,type Task,type Status,type Operation} from '@/lib/board';
const labels:Record<Status,string>={pending:'待开始',in_progress:'进行中',blocked:'已阻塞',paused:'已暂停',done:'已完成'};
const fmt=(s:string)=>new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
export default function Page(){
 useBoardWebTools();
 const [board,setBoard]=useState<Board|null>(null),[revision,setRevision]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[project,setProject]=useState('all'),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[trash,setTrash]=useState(false),[collapsed,setCollapsed]=useState<string[]>([]),[selected,setSelected]=useState<Task|null>(null),[creating,setCreating]=useState(false),[history,setHistory]=useState(false);
 async function load(){try{const r=await fetch('/api/board');if(r.status===401){window.location.href='/signin-with-chatgpt?return_to=%2F';return;}const d=await r.json() as {board:Board;revision:number;error?:string};if(!r.ok)throw Error(d.error);setBoard(d.board);setRevision(d.revision);setError('');}catch(e){setError(e instanceof Error?e.message:'加载失败');}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(selected)return;const timer=setInterval(()=>void load(),30000);return()=>clearInterval(timer);},[selected]);
 async function save(operation:Operation){setBusy(true);setError('');try{const r=await fetch('/api/board',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision,operation})});const d=await r.json() as {board:Board;revision:number;error?:string};if(!r.ok)throw Error(d.error);setBoard(d.board);setRevision(d.revision);setSelected(null);setCreating(false);}catch(e){setError(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}}
 const active=board?.tasks.filter(t=>!t.deletedAt)||[],roots=active.filter(t=>!t.parentId);
 function under(t:Task,id:string):boolean{if(t.id===id)return true;const parent=board?.tasks.find(p=>p.id===t.parentId);return parent?under(parent,id):false;}
 const scoped=active.filter(t=>project==='all'||under(t,project)),leaves=scoped.filter(t=>!active.some(c=>c.parentId===t.id)),counts=Object.fromEntries(statuses.map(s=>[s,leaves.filter(t=>t.status===s).length]));
 function matches(t:Task){return (filter==='all'||t.status===filter)&&(!search||`${t.title} ${t.detail}`.toLowerCase().includes(search.toLowerCase()));}
 function visible(t:Task):boolean{return matches(t)||(board?.tasks.some(c=>c.parentId===t.id&&!c.deletedAt&&visible(c))||false);}
 function start(parentId:string|null){setCreating(true);setSelected({id:crypto.randomUUID(),parentId,title:'',status:'pending',detail:'',next:'',evidence:'',updatedAt:new Date().toISOString(),deletedAt:null,locks:[]});}
 function node(t:Task,level=0){const children=active.filter(c=>c.parentId===t.id);if(!visible(t))return null;const shut=collapsed.includes(t.id);return <div key={t.id} className="branch"><div className={'task-row '+(!t.parentId?'project-row':'')} style={{paddingLeft:`${16+Math.min(level,5)*22}px`}}><button className="toggle" aria-label={shut?'展开子任务':'收起子任务'} disabled={!children.length} onClick={()=>setCollapsed(shut?collapsed.filter(x=>x!==t.id):[...collapsed,t.id])}>{children.length?(shut?<ChevronRight size={17}/>:<ChevronDown size={17}/>):<span className={'small-mark '+t.status}/>}</button><button className="task-main" onClick={()=>{setCreating(false);setSelected(t);}}><span className="task-title">{t.title}{t.locks.length>0&&<LockKeyhole size={13}/>}</span><span className="task-summary">{t.next||t.detail||'尚未填写下一步'}</span></button><span className={'badge '+t.status}>{labels[t.status]}</span><span className="time">{fmt(t.updatedAt)}</span><button className="add-sub" aria-label={'为'+t.title+'添加子任务'} onClick={()=>start(t.id)}><Plus size={17}/></button></div>{!shut&&children.map(c=>node(c,level+1))}</div>}
 return <div className="shell"><aside className="sidebar"><div className="brand"><span className="brand-icon"><Layers size={22}/></span><div>星序<span>饭饭的项目工作台</span></div></div><nav><button className={project==='all'&&!trash?'nav active':'nav'} onClick={()=>{setProject('all');setTrash(false);}}><FolderKanban size={18}/>全部项目<span>{roots.length}</span></button><div className="nav-label">项目</div>{roots.map(p=><button key={p.id} className={project===p.id&&!trash?'nav active':'nav'} onClick={()=>{setProject(p.id);setTrash(false);}}><span className="project-initial">{p.title[0]}</span>{p.title}</button>)}<button className="nav muted" onClick={()=>start(null)}><Plus size={18}/>添加项目</button></nav><div className="sidebar-bottom"><button className={'nav '+(trash?'active':'')} onClick={()=>setTrash(true)}><Trash2 size={17}/>回收站<span>{board?.tasks.filter(t=>t.deletedAt).length||0}</span></button><p>私人工作台<br/>时间显示为北京时间</p></div></aside><main><header><div className="breadcrumb">工作台 <span>/</span> {trash?'回收站':project==='all'?'全部项目':roots.find(p=>p.id===project)?.title}</div><button className="icon-button mobile-trash" aria-label="打开回收站" onClick={()=>setTrash(true)}><Trash2 size={18}/></button><button className="icon-button" aria-label="刷新看板" onClick={()=>void load()}><RefreshCw size={18}/></button></header><section className="content"><div className="heading"><div><div className="eyebrow">PROJECT OVERVIEW</div><h1>{trash?'回收站':project==='all'?'把进展看清楚':roots.find(p=>p.id===project)?.title}</h1><p>{trash?'删除的任务可恢复；删除看板记录不会自动终止正在运行的工作':'从项目到每个子任务，查看状态、证据和下一步'}</p></div><button className="primary" onClick={()=>start(project==='all'?null:project)}><Plus size={18}/>{project==='all'?'新建项目':'添加任务'}</button></div>{error&&<div role="alert" className="error">{error}<button onClick={()=>void load()}>刷新</button></div>}
 {!board?<div className="empty">{error?'暂时无法加载，请重试':'正在读取你的项目…'}</div>:<>{!trash&&<><div className="stats">{(['in_progress','blocked','paused','done'] as Status[]).map(s=><button key={s} className={'stat '+(filter===s?'chosen':'')} onClick={()=>setFilter(filter===s?'all':s)}><span className={'stat-label '+s}>{labels[s]}</span><strong>{counts[s]}</strong><span>个末级任务</span></button>)}</div><div className="progress-caption"><span>{counts.done} / {leaves.length} 个末级任务已完成</span><Progress className="bar" value={leaves.length?counts.done/leaves.length*100:0} aria-label="末级任务完成比例"/><span>按当前任务清单统计</span></div></>}
 <div className="work-list"><div className="toolbar"><Tabs value={history?"history":"tasks"} onValueChange={v=>setHistory(v==="history")}><TabsList variant="line" className="tabs"><TabsTrigger value="tasks">任务层级</TabsTrigger><TabsTrigger value="history"><Activity size={15}/>变更记录</TabsTrigger></TabsList></Tabs><div className="tools"><label className="search"><Search size={17}/><input placeholder="搜索任务" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="筛选状态" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">所有状态</option>{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div></div>{history?<div className="events">{board.events.length?board.events.map((e,i)=><div key={i}><span>{fmt(e.at)}</span><b>{e.actor==='user'?'你':'饭饭'}</b>{e.text}</div>):<div className="empty">尚无变更记录</div>}</div>:trash?<div>{board.tasks.filter(t=>t.deletedAt&&matches(t)).map(t=><div className="trash-row" key={t.id}><div><strong>{t.title}</strong><small>{fmt(t.deletedAt!)} 删除</small></div><button onClick={()=>void save({action:'restore',id:t.id})} disabled={busy}><RotateCcw size={15}/>恢复</button></div>)}{!board.tasks.some(t=>t.deletedAt)&&<div className="empty">回收站是空的</div>}</div>:<><div className="column-head"><span>项目 / 任务</span><span>状态</span><span>最近更新</span></div>{(project==='all'?roots:roots.filter(p=>p.id===project)).map(t=>node(t))}{!scoped.some(matches)&&<div className="empty">没有匹配的任务</div>}</>}</div><footer>状态以记录的验证结果为准 · 点击任务查看详情和证据 · 手动修改的字段会受到保护</footer></>}
 </section></main><Sheet open={!!selected} onOpenChange={o=>!o&&!busy&&setSelected(null)}>{selected&&<SheetContent className="drawer" showCloseButton={false}><SheetTitle className="sr-only">{creating?"新建任务":"编辑任务"}</SheetTitle><SheetDescription className="sr-only">查看进展、编辑任务或移入可恢复的回收站</SheetDescription><div className="drawer-head"><span>{creating?'新建':'任务详情'}</span><button className="icon-button" aria-label="关闭" onClick={()=>setSelected(null)}><X size={20}/></button></div><form onSubmit={e=>{e.preventDefault();const patch=Object.fromEntries((['title','status','detail','next','evidence'] as const).filter(k=>creating||selected[k]!==board?.tasks.find(t=>t.id===selected.id)?.[k]).map(k=>[k,selected[k]]));void save({action:creating?'create':'update',id:selected.id,parentId:selected.parentId,patch});}}><label>名称<input required maxLength={160} value={selected.title} onChange={e=>setSelected({...selected,title:e.target.value})}/></label><label>状态<select value={selected.status} onChange={e=>setSelected({...selected,status:e.target.value as Status})}>{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label>已知进展 / 阻塞原因<textarea rows={6} maxLength={5000} value={selected.detail} onChange={e=>setSelected({...selected,detail:e.target.value})}/></label><label>下一步<textarea rows={3} maxLength={5000} value={selected.next} onChange={e=>setSelected({...selected,next:e.target.value})}/></label><label>验证证据 / 链接<textarea rows={2} maxLength={5000} value={selected.evidence} onChange={e=>setSelected({...selected,evidence:e.target.value})}/></label>{/^https:\/\//.test(selected.evidence)&&!/[\s]/.test(selected.evidence)&&<a className="evidence" href={selected.evidence} target="_blank" rel="noreferrer">打开证据<ExternalLink size={14}/></a>}{selected.locks.length>0&&<div className="protected"><LockKeyhole size={16}/>部分字段已由你修改，自动同步不会覆盖<button type="button" onClick={()=>void save({action:'unlock',id:selected.id})} disabled={busy}>允许重新同步</button></div>}{error&&<p role="alert" className="error">{error}</p>}<div className="drawer-actions"><button className="primary" disabled={busy}>{busy?'保存中…':'保存修改'}</button>{!creating&&<button type="button" className="danger" disabled={busy} onClick={()=>{if(confirm('将这个任务及所有子任务移入回收站？可以恢复。这不会停止正在运行的工作。'))void save({action:'delete',id:selected.id});}}><Trash2 size={16}/>删除</button>}</div></form></SheetContent>}</Sheet></div>;
}
